"""initial schema

Revision ID: c30a32b605ab
Revises: 
Create Date: 2026-02-06 05:14:12.517593
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from src.adapters.persistence.orm import types  # Custom TypeDecorators
from sqlalchemy.dialects import postgresql

revision: str = 'c30a32b605ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', types.HouseholdIdType(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_households'))
    )
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('aggregate_type', sa.String(length=255), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox'))
    )
    op.create_index('ix_outbox_unprocessed', 'outbox', ['processed_at'], unique=False, postgresql_where=sa.text('processed_at IS NULL'))
    op.create_table('users',
    sa.Column('id', types.UserIdType(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('household_id', types.HouseholdIdType(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_users_household_id_households')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_household_id', 'users', ['household_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', types.AccountIdType(length=36), nullable=False),
    sa.Column('user_id', types.UserIdType(length=36), nullable=False),
    sa.Column('household_id', types.HouseholdIdType(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', types.AccountTypeEnum(length=50), nullable=False),
    sa.Column('status', types.AccountStatusEnum(length=20), nullable=False),
    sa.Column('subtype', types.AccountSubtypeEnum(length=50), nullable=True),
    sa.Column('opening_balance_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('opening_balance_currency', sa.String(length=3), nullable=False),
    sa.Column('opening_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('credit_limit_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('credit_limit_currency', sa.String(length=3), nullable=True),
    sa.Column('apr', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rewards_value', sa.Numeric(precision=19, scale=0), nullable=True),
    sa.Column('rewards_unit', sa.String(length=100), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('institution_website', sa.String(length=500), nullable=True),
    sa.Column('institution_phone', sa.String(length=50), nullable=True),
    sa.Column('institution_notes', sa.Text(), nullable=True),
    sa.Column('encrypted_account_number', sa.Text(), nullable=True),
    sa.Column('closing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', types.UserIdType(length=36), nullable=True),
    sa.Column('updated_by', types.UserIdType(length=36), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_accounts_household_id_households')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_index('ix_accounts_household_id', 'accounts', ['household_id'], unique=False)
    op.create_index('ix_accounts_user_id', 'accounts', ['user_id'], unique=False)
    op.create_index('ix_accounts_user_status', 'accounts', ['user_id', 'status'], unique=False)
    op.create_index('ix_accounts_user_type', 'accounts', ['user_id', 'account_type'], unique=False)
    op.create_table('categories',
    sa.Column('id', types.CategoryIdType(length=36), nullable=False),
    sa.Column('user_id', types.UserIdType(length=36), nullable=False),
    sa.Column('household_id', types.HouseholdIdType(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', types.CategoryIdType(length=36), nullable=True),
    sa.Column('category_type', sa.String(length=10), server_default='expense', nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_categories_household_id_households')),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index('ix_categories_household_id', 'categories', ['household_id'], unique=False)
    op.create_index('ix_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_index('ix_categories_user_id', 'categories', ['user_id'], unique=False)
    op.create_index('ix_categories_user_system', 'categories', ['user_id', 'is_system'], unique=False)
    op.create_table('encrypted_secrets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('secret_type', sa.String(length=50), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_encrypted_secrets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encrypted_secrets'))
    )
    op.create_index('ix_encrypted_secrets_user_type', 'encrypted_secrets', ['user_id', 'secret_type'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', types.UserIdType(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_family', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index('ix_refresh_tokens_family', 'refresh_tokens', ['token_family'], unique=False)
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('payees',
    sa.Column('id', types.PayeeIdType(length=36), nullable=False),
    sa.Column('user_id', types.UserIdType(length=36), nullable=False),
    sa.Column('household_id', types.HouseholdIdType(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('default_category_id', types.CategoryIdType(length=36), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_category_id'], ['categories.id'], name=op.f('fk_payees_default_category_id_categories')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_payees_household_id_households')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payees_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payees'))
    )
    op.create_index('ix_payees_household_id', 'payees', ['household_id'], unique=False)
    op.create_index('ix_payees_user_id', 'payees', ['user_id'], unique=False)
    op.create_index('ix_payees_user_normalized', 'payees', ['user_id', 'normalized_name'], unique=False)
    op.create_table('transactions',
    sa.Column('id', types.TransactionIdType(length=36), nullable=False),
    sa.Column('user_id', types.UserIdType(length=36), nullable=False),
    sa.Column('account_id', types.AccountIdType(length=36), nullable=False),
    sa.Column('household_id', types.HouseholdIdType(length=36), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', types.TransactionStatusEnum(length=20), nullable=False),
    sa.Column('source', types.TransactionSourceEnum(length=20), nullable=False),
    sa.Column('payee_id', types.PayeeIdType(length=36), nullable=True),
    sa.Column('payee_name', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('source_transaction_id', types.TransactionIdType(length=36), nullable=True),
    sa.Column('source_split_id', types.SplitIdType(length=36), nullable=True),
    sa.Column('is_mirror', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_transactions_household_id_households')),
    sa.ForeignKeyConstraint(['payee_id'], ['payees.id'], name=op.f('fk_transactions_payee_id_payees')),
    sa.ForeignKeyConstraint(['source_transaction_id'], ['transactions.id'], name=op.f('fk_transactions_source_transaction_id_transactions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index('ix_transactions_account_effective_date', 'transactions', ['account_id', 'effective_date'], unique=False)
    op.create_index('ix_transactions_account_id', 'transactions', ['account_id'], unique=False)
    op.create_index('ix_transactions_household_id', 'transactions', ['household_id'], unique=False)
    op.create_index('ix_transactions_search', 'transactions', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_transactions_source_split_id', 'transactions', ['source_split_id'], unique=False)
    op.create_index('ix_transactions_source_transaction', 'transactions', ['source_transaction_id'], unique=False)
    op.create_index('ix_transactions_user_effective_date', 'transactions', ['user_id', 'effective_date'], unique=False)
    op.create_index('ix_transactions_user_id', 'transactions', ['user_id'], unique=False)
    op.create_table('split_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('split_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', types.TransactionIdType(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category_id', types.CategoryIdType(length=36), nullable=True),
    sa.Column('transfer_account_id', types.AccountIdType(length=36), nullable=True),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_split_lines_category_id_categories')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_split_lines_transaction_id_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['accounts.id'], name=op.f('fk_split_lines_transfer_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_split_lines'))
    )
    op.create_index('ix_split_lines_category_id', 'split_lines', ['category_id'], unique=False)
    op.create_index('ix_split_lines_split_id', 'split_lines', ['split_id'], unique=True)
    op.create_index('ix_split_lines_transaction_id', 'split_lines', ['transaction_id'], unique=False)
    op.create_index('ix_split_lines_transfer_account', 'split_lines', ['transfer_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_split_lines_transfer_account', table_name='split_lines')
    op.drop_index('ix_split_lines_transaction_id', table_name='split_lines')
    op.drop_index('ix_split_lines_split_id', table_name='split_lines')
    op.drop_index('ix_split_lines_category_id', table_name='split_lines')
    op.drop_table('split_lines')
    op.drop_index('ix_transactions_user_id', table_name='transactions')
    op.drop_index('ix_transactions_user_effective_date', table_name='transactions')
    op.drop_index('ix_transactions_source_transaction', table_name='transactions')
    op.drop_index('ix_transactions_source_split_id', table_name='transactions')
    op.drop_index('ix_transactions_search', table_name='transactions', postgresql_using='gin')
    op.drop_index('ix_transactions_household_id', table_name='transactions')
    op.drop_index('ix_transactions_account_id', table_name='transactions')
    op.drop_index('ix_transactions_account_effective_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_payees_user_normalized', table_name='payees')
    op.drop_index('ix_payees_user_id', table_name='payees')
    op.drop_index('ix_payees_household_id', table_name='payees')
    op.drop_table('payees')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_encrypted_secrets_user_type', table_name='encrypted_secrets')
    op.drop_table('encrypted_secrets')
    op.drop_index('ix_categories_user_system', table_name='categories')
    op.drop_index('ix_categories_user_id', table_name='categories')
    op.drop_index('ix_categories_parent_id', table_name='categories')
    op.drop_index('ix_categories_household_id', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_accounts_user_type', table_name='accounts')
    op.drop_index('ix_accounts_user_status', table_name='accounts')
    op.drop_index('ix_accounts_user_id', table_name='accounts')
    op.drop_index('ix_accounts_household_id', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_users_household_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_outbox_unprocessed', table_name='outbox', postgresql_where=sa.text('processed_at IS NULL'))
    op.drop_table('outbox')
    op.drop_table('households')
    # ### end Alembic commands ###
