/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Check
     * @description Health check endpoint.
     *
     *     Returns:
     *         Health status with environment info
     */
    get: operations['health_check_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness Check
     * @description Readiness check for Kubernetes.
     *     Checks if app is ready to receive traffic.
     *
     *     TODO: Add database connectivity check in Phase 4
     */
    get: operations['readiness_check_ready_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register new user
     * @description Register a new user.
     *
     *     Always returns 202 to prevent email enumeration attacks.
     *     On duplicate email, returns 202 with a generic user_id.
     *
     *     Args:
     *         request: Registration data (email, password, display_name).
     *         service: AuthService from dependency injection.
     *
     *     Returns:
     *         RegisterResponse with user_id and confirmation message.
     */
    post: operations['register_auth_register_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login (OAuth2 compatible)
     * @description Authenticate user and return tokens.
     *
     *     OAuth2-compatible endpoint. Uses username field for email.
     *     Access token returned in response body, refresh token set as HttpOnly cookie.
     *
     *     Args:
     *         response: FastAPI response for setting cookies.
     *         form_data: OAuth2 form with username (email) and password.
     *         remember_me: If True, refresh token cookie is persistent (30 days).
     *                      If False, refresh token cookie is session-only (deleted on browser close).
     *         service: AuthService from dependency injection.
     *
     *     Returns:
     *         TokenResponse with access_token.
     *
     *     Raises:
     *         HTTPException: 401 if credentials are invalid.
     */
    post: operations['login_auth_token_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh access token
     * @description Exchange refresh token for new access token.
     *
     *     Reads refresh token from HttpOnly cookie. Rotates the refresh token
     *     (old token invalidated, new token issued in cookie).
     *
     *     Args:
     *         response: FastAPI response for setting new cookie.
     *         service: AuthService from dependency injection.
     *         refresh_token: Refresh token from cookie.
     *
     *     Returns:
     *         TokenResponse with new access_token.
     *
     *     Raises:
     *         HTTPException: 401 if refresh token is missing, invalid, or expired.
     */
    post: operations['refresh_token_auth_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Verify email address
     * @description Verify a user's email address using a signed token.
     *
     *     Args:
     *         token: The verification token from the email link.
     *         service: AuthService from dependency injection.
     *
     *     Returns:
     *         VerifyEmailResponse with user info.
     *
     *     Raises:
     *         HTTPException: 400 if token is invalid or expired.
     */
    get: operations['verify_email_auth_verify_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout (clear refresh token)
     * @description Clear refresh token cookie.
     *
     *     Args:
     *         response: FastAPI response for clearing cookie.
     */
    post: operations['logout_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current user profile
     * @description Get authenticated user's profile with household info.
     *
     *     Returns user metadata (email, display_name, email_verified, created_at)
     *     and nested household object (id, name, is_owner flag).
     *
     *     Args:
     *         service: AuthService from dependency injection.
     *         current_user: CurrentUser extracted from JWT.
     *
     *     Returns:
     *         UserProfileResponse with user profile and household info.
     *
     *     Raises:
     *         HTTPException: 404 if user not found (should not happen with valid JWT).
     */
    get: operations['get_current_user_profile_auth_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/checking': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create checking account
     * @description Create a new checking account.
     *
     *     Args:
     *         request: Checking account creation data.
     *         service: AccountService from dependency injection.
     *         current_user: Authenticated user context from JWT.
     *
     *     Returns:
     *         Created account details.
     *
     *     Raises:
     *         HTTPException: On validation or creation failure.
     */
    post: operations['create_checking_account_api_v1_accounts_checking_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/savings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create savings account
     * @description Create a new savings account.
     *
     *     Args:
     *         request: Savings account creation data.
     *         service: AccountService from dependency injection.
     *         current_user: Authenticated user context from JWT.
     *
     *     Returns:
     *         Created account details.
     *
     *     Raises:
     *         HTTPException: On validation or creation failure.
     */
    post: operations['create_savings_account_api_v1_accounts_savings_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/credit-card': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create credit card account
     * @description Create a new credit card account.
     *
     *     Args:
     *         request: Credit card account creation data.
     *         service: AccountService from dependency injection.
     *         current_user: Authenticated user context from JWT.
     *
     *     Returns:
     *         Created account details.
     *
     *     Raises:
     *         HTTPException: On validation or creation failure.
     */
    post: operations['create_credit_card_account_api_v1_accounts_credit_card_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/loan': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create loan account
     * @description Create a new loan account.
     *
     *     Args:
     *         request: Loan account creation data.
     *         service: AccountService from dependency injection.
     *         current_user: Authenticated user context from JWT.
     *
     *     Returns:
     *         Created account details.
     *
     *     Raises:
     *         HTTPException: On validation or creation failure.
     */
    post: operations['create_loan_account_api_v1_accounts_loan_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/brokerage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create brokerage account
     * @description Create a new brokerage account.
     *
     *     Args:
     *         request: Brokerage account creation data.
     *         service: AccountService from dependency injection.
     *         current_user: Authenticated user context from JWT.
     *
     *     Returns:
     *         Created account details.
     *
     *     Raises:
     *         HTTPException: On validation or creation failure.
     */
    post: operations['create_brokerage_account_api_v1_accounts_brokerage_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/ira': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create IRA account
     * @description Create a new IRA account.
     *
     *     Args:
     *         request: IRA account creation data.
     *         service: AccountService from dependency injection.
     *         current_user: Authenticated user context from JWT.
     *
     *     Returns:
     *         Created account details.
     *
     *     Raises:
     *         HTTPException: On validation or creation failure.
     */
    post: operations['create_ira_account_api_v1_accounts_ira_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/rewards': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create rewards account
     * @description Create a new rewards account.
     *
     *     Args:
     *         request: Rewards account creation data.
     *         service: AccountService from dependency injection.
     *         current_user: Authenticated user context from JWT.
     *
     *     Returns:
     *         Created account details.
     *
     *     Raises:
     *         HTTPException: On validation or creation failure.
     */
    post: operations['create_rewards_account_api_v1_accounts_rewards_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List household accounts
     * @description List all accounts for the current user's household.
     *
     *     Args:
     *         service: AccountService from dependency injection.
     *         current_user: Authenticated user context from JWT.
     *         status_filter: Optional status filter (active, closed).
     *         type_filter: Optional account type filter.
     *
     *     Returns:
     *         List of matching accounts.
     */
    get: operations['list_accounts_api_v1_accounts_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/{account_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get account by ID
     * @description Get a single account by ID.
     *
     *     Verifies the account belongs to the user's household.
     *
     *     Args:
     *         account_id: The account identifier.
     *         service: AccountService from dependency injection.
     *         current_user: Authenticated user context from JWT.
     *
     *     Returns:
     *         Account details.
     *
     *     Raises:
     *         HTTPException: If account not found or belongs to different household.
     */
    get: operations['get_account_api_v1_accounts__account_id__get'];
    put?: never;
    post?: never;
    /**
     * Delete account
     * @description Delete an account.
     *
     *     Only accounts without transactions can be deleted.
     *     Accounts with transaction history should be closed instead.
     *
     *     Args:
     *         account_id: The account identifier.
     *         service: AccountService from dependency injection.
     *         current_user: Authenticated user context from JWT.
     *
     *     Raises:
     *         HTTPException: If account not found or has transactions.
     */
    delete: operations['delete_account_api_v1_accounts__account_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update account
     * @description Update an account's editable fields.
     *
     *     Only name, institution, and notes can be updated.
     *     Opening balance, type, and other core fields are immutable.
     *
     *     Args:
     *         account_id: The account identifier.
     *         request: Fields to update.
     *         service: AccountService from dependency injection.
     *         current_user: Authenticated user context from JWT.
     *
     *     Returns:
     *         Updated account details.
     *
     *     Raises:
     *         HTTPException: If account not found or validation fails.
     */
    patch: operations['update_account_api_v1_accounts__account_id__patch'];
    trace?: never;
  };
  '/api/v1/accounts/{account_id}/close': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Close account
     * @description Close an active account.
     *
     *     Closed accounts retain their data but cannot be used for transactions.
     *     They can be reopened later if needed.
     *
     *     Args:
     *         account_id: The account identifier.
     *         service: AccountService from dependency injection.
     *         current_user: Authenticated user context from JWT.
     *
     *     Returns:
     *         Closed account details.
     *
     *     Raises:
     *         HTTPException: If account not found or already closed.
     */
    post: operations['close_account_api_v1_accounts__account_id__close_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/{account_id}/reopen': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reopen closed account
     * @description Reopen a closed account.
     *
     *     Returns the account to active status.
     *
     *     Args:
     *         account_id: The account identifier.
     *         service: AccountService from dependency injection.
     *         current_user: Authenticated user context from JWT.
     *
     *     Returns:
     *         Reopened account details.
     *
     *     Raises:
     *         HTTPException: If account not found or not closed.
     */
    post: operations['reopen_account_api_v1_accounts__account_id__reopen_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Categories
     * @description List all categories for the current user.
     */
    get: operations['list_categories_api_v1_categories_get'];
    put?: never;
    /**
     * Create Category
     * @description Create a new category.
     */
    post: operations['create_category_api_v1_categories_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/categories/tree': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Category Tree
     * @description Get categories organized as a tree structure.
     */
    get: operations['get_category_tree_api_v1_categories_tree_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/categories/{category_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Category
     * @description Get a category by ID.
     */
    get: operations['get_category_api_v1_categories__category_id__get'];
    put?: never;
    post?: never;
    /**
     * Delete Category
     * @description Delete a category.
     */
    delete: operations['delete_category_api_v1_categories__category_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Category
     * @description Update a category.
     */
    patch: operations['update_category_api_v1_categories__category_id__patch'];
    trace?: never;
  };
  '/api/v1/transactions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Transactions
     * @description List transactions with filtering and search.
     */
    get: operations['list_transactions_api_v1_transactions_get'];
    put?: never;
    /**
     * Create Transaction
     * @description Create a new transaction with splits.
     */
    post: operations['create_transaction_api_v1_transactions_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/transactions/{transaction_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Transaction
     * @description Get a transaction by ID.
     */
    get: operations['get_transaction_api_v1_transactions__transaction_id__get'];
    put?: never;
    post?: never;
    /**
     * Delete Transaction
     * @description Delete a transaction (and its mirrors if source).
     */
    delete: operations['delete_transaction_api_v1_transactions__transaction_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Transaction
     * @description Update transaction fields.
     *
     *     Supports two modes:
     *     1. Metadata only: Update dates, memo, payee, check_number (no splits/amount)
     *     2. Full update: Include splits and amount to change financial allocations
     *
     *     When updating splits, mirror transactions are automatically synced.
     */
    patch: operations['update_transaction_api_v1_transactions__transaction_id__patch'];
    trace?: never;
  };
  '/api/v1/transactions/{transaction_id}/clear': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mark Transaction Cleared
     * @description Mark transaction as cleared.
     */
    post: operations['mark_transaction_cleared_api_v1_transactions__transaction_id__clear_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/transactions/{transaction_id}/reconcile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mark Transaction Reconciled
     * @description Mark transaction as reconciled.
     */
    post: operations['mark_transaction_reconciled_api_v1_transactions__transaction_id__reconcile_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AccountListResponse
     * @description Response schema for listing accounts.
     */
    AccountListResponse: {
      /**
       * Accounts
       * @description List of accounts
       */
      accounts: components['schemas']['AccountResponse'][];
      /**
       * Total
       * @description Total number of accounts matching filters
       */
      total: number;
    };
    /**
     * AccountResponse
     * @description Response schema for a single account.
     *
     *     Masks account numbers for security (shows only last 4 digits).
     *     Current balance equals opening balance until Phase 3 transactions.
     */
    AccountResponse: {
      /**
       * Id
       * @description Account ID (prefixed)
       */
      id: string;
      /**
       * User Id
       * @description Owner user ID
       */
      user_id: string;
      /**
       * Name
       * @description Account display name
       */
      name: string;
      /** @description Account type */
      account_type: components['schemas']['AccountType'];
      /** @description Account status */
      status: components['schemas']['AccountStatus'];
      /** @description Opening balance */
      opening_balance: components['schemas']['MoneySchema'];
      /** @description Current balance (equals opening until Phase 3) */
      current_balance: components['schemas']['MoneySchema'];
      /**
       * Opening Date
       * Format: date-time
       * @description Date account was opened
       */
      opening_date: string;
      /** @description Account subtype */
      subtype?: components['schemas']['AccountSubtype'] | null;
      /** @description Credit limit */
      credit_limit?: components['schemas']['MoneySchema'] | null;
      /** @description Available credit */
      available_credit?: components['schemas']['MoneySchema'] | null;
      /**
       * Apr
       * @description Annual percentage rate
       */
      apr?: string | null;
      /**
       * Term Months
       * @description Loan term in months
       */
      term_months?: number | null;
      /**
       * Due Date
       * @description Due date for loans
       */
      due_date?: string | null;
      /** @description Rewards balance */
      rewards_balance?: components['schemas']['RewardsBalanceSchema-Output'] | null;
      /** @description Institution details */
      institution?: components['schemas']['InstitutionSchema'] | null;
      /**
       * Account Number Last4
       * @description Last 4 digits of account number
       */
      account_number_last4?: string | null;
      /**
       * Closing Date
       * @description Date account was closed
       */
      closing_date?: string | null;
      /**
       * Notes
       * @description Account notes
       */
      notes?: string | null;
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       * @description Last update timestamp
       */
      updated_at: string;
    };
    /**
     * AccountStatus
     * @description Account lifecycle status.
     *
     *     Accounts start as ACTIVE and can be CLOSED. Closed accounts
     *     can be reopened, returning to ACTIVE status.
     * @enum {string}
     */
    AccountStatus: 'active' | 'closed';
    /**
     * AccountSubtype
     * @description Optional subtypes for type-specific domain logic.
     *
     *     Subtypes provide additional classification within a main account type.
     *     For example, IRA accounts can be Traditional, Roth, or SEP.
     * @enum {string}
     */
    AccountSubtype:
      | 'traditional_ira'
      | 'roth_ira'
      | 'sep_ira'
      | 'mortgage'
      | 'auto_loan'
      | 'personal_loan'
      | 'line_of_credit';
    /**
     * AccountType
     * @description Supported account types.
     *
     *     Each value represents a distinct category of financial account
     *     with its own validation rules and behavior.
     * @enum {string}
     */
    AccountType: 'checking' | 'savings' | 'credit_card' | 'loan' | 'brokerage' | 'ira' | 'rewards';
    /** Body_login_auth_token_post */
    Body_login_auth_token_post: {
      /**
       * Remember Me
       * @default false
       */
      remember_me: boolean;
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
    };
    /**
     * CategoryListResponse
     * @description Response for listing categories.
     */
    CategoryListResponse: {
      /** Categories */
      categories: components['schemas']['CategoryResponse'][];
      /** Total */
      total: number;
    };
    /**
     * CategoryResponse
     * @description Response schema for a category.
     */
    CategoryResponse: {
      /** Id */
      id: string;
      /** User Id */
      user_id: string;
      /** Name */
      name: string;
      /** Parent Id */
      parent_id: string | null;
      /** Category Type */
      category_type: string;
      /** Is System */
      is_system: boolean;
      /** Is Hidden */
      is_hidden: boolean;
      /** Sort Order */
      sort_order: number;
      /** Icon */
      icon: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * CategoryTreeResponse
     * @description Response for category tree structure.
     */
    CategoryTreeResponse: {
      /** Root */
      root: components['schemas']['CategoryResponse'][];
      /** Children */
      children: {
        [key: string]: components['schemas']['CategoryResponse'][];
      };
    };
    /**
     * CreateBrokerageAccountRequest
     * @description Request schema for creating a brokerage account.
     */
    CreateBrokerageAccountRequest: {
      /**
       * Name
       * @description Account display name
       */
      name: string;
      /** @description Initial cash balance */
      opening_balance: components['schemas']['MoneySchema'];
      /**
       * Opening Date
       * @description Date account was opened (defaults to now)
       */
      opening_date?: string | null;
      /** @description Financial institution details */
      institution?: components['schemas']['InstitutionSchema'] | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * CreateCategoryRequest
     * @description Request to create a new category.
     */
    CreateCategoryRequest: {
      /** Name */
      name: string;
      /**
       * Parent Id
       * @description Parent category ID for subcategories
       */
      parent_id?: string | null;
      /**
       * Icon
       * @description Emoji or icon name
       */
      icon?: string | null;
      /**
       * Category Type
       * @description Category type: 'income' or 'expense'
       * @default expense
       */
      category_type: string;
    };
    /**
     * CreateCheckingAccountRequest
     * @description Request schema for creating a checking account.
     */
    CreateCheckingAccountRequest: {
      /**
       * Name
       * @description Account display name
       */
      name: string;
      /** @description Initial balance */
      opening_balance: components['schemas']['MoneySchema'];
      /**
       * Opening Date
       * @description Date account was opened (defaults to now)
       */
      opening_date?: string | null;
      /** @description Financial institution details */
      institution?: components['schemas']['InstitutionSchema'] | null;
      /**
       * Account Number
       * @description Account number (will be encrypted)
       */
      account_number?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * CreateCreditCardAccountRequest
     * @description Request schema for creating a credit card account.
     */
    CreateCreditCardAccountRequest: {
      /**
       * Name
       * @description Account display name
       */
      name: string;
      /** @description Initial balance (current charges) */
      opening_balance: components['schemas']['MoneySchema'];
      /** @description Credit limit */
      credit_limit: components['schemas']['MoneySchema'];
      /**
       * Opening Date
       * @description Date account was opened (defaults to now)
       */
      opening_date?: string | null;
      /** @description Financial institution details */
      institution?: components['schemas']['InstitutionSchema'] | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * CreateIraAccountRequest
     * @description Request schema for creating an IRA account.
     */
    CreateIraAccountRequest: {
      /**
       * Name
       * @description Account display name
       */
      name: string;
      /** @description Initial balance */
      opening_balance: components['schemas']['MoneySchema'];
      /** @description IRA type (traditional_ira, roth_ira, sep_ira) */
      subtype?: components['schemas']['AccountSubtype'] | null;
      /**
       * Opening Date
       * @description Date account was opened (defaults to now)
       */
      opening_date?: string | null;
      /** @description Financial institution details */
      institution?: components['schemas']['InstitutionSchema'] | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * CreateLoanAccountRequest
     * @description Request schema for creating a loan account.
     */
    CreateLoanAccountRequest: {
      /**
       * Name
       * @description Account display name
       */
      name: string;
      /** @description Initial loan balance (principal) */
      opening_balance: components['schemas']['MoneySchema'];
      /** @description Loan type (mortgage, auto, personal, line_of_credit) */
      subtype?: components['schemas']['AccountSubtype'] | null;
      /**
       * Apr
       * @description Annual percentage rate as decimal (e.g., 0.0599 for 5.99%)
       */
      apr?: number | string | null;
      /**
       * Term Months
       * @description Loan term in months
       */
      term_months?: number | null;
      /**
       * Due Date
       * @description Final payment due date
       */
      due_date?: string | null;
      /**
       * Opening Date
       * @description Date loan originated (defaults to now)
       */
      opening_date?: string | null;
      /** @description Financial institution details */
      institution?: components['schemas']['InstitutionSchema'] | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * CreateRewardsAccountRequest
     * @description Request schema for creating a rewards account.
     */
    CreateRewardsAccountRequest: {
      /**
       * Name
       * @description Account display name
       */
      name: string;
      /** @description Initial rewards balance (points/miles) */
      rewards_balance: components['schemas']['RewardsBalanceSchema-Input'];
      /**
       * Opening Date
       * @description Date account was opened (defaults to now)
       */
      opening_date?: string | null;
      /** @description Rewards program provider */
      institution?: components['schemas']['InstitutionSchema'] | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * CreateSavingsAccountRequest
     * @description Request schema for creating a savings account.
     */
    CreateSavingsAccountRequest: {
      /**
       * Name
       * @description Account display name
       */
      name: string;
      /** @description Initial balance */
      opening_balance: components['schemas']['MoneySchema'];
      /**
       * Opening Date
       * @description Date account was opened (defaults to now)
       */
      opening_date?: string | null;
      /** @description Financial institution details */
      institution?: components['schemas']['InstitutionSchema'] | null;
      /**
       * Account Number
       * @description Account number (will be encrypted)
       */
      account_number?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * CreateTransactionRequest
     * @description Request to create a transaction.
     */
    CreateTransactionRequest: {
      /**
       * Account Id
       * @description Account for this transaction
       */
      account_id: string;
      /**
       * Effective Date
       * Format: date
       * @description When transaction logically occurred
       */
      effective_date: string;
      /**
       * Posted Date
       * @description When transaction cleared (defaults to effective_date)
       */
      posted_date?: string | null;
      /** @description Net flow (positive=inflow, negative=outflow) */
      amount: components['schemas']['src__adapters__api__schemas__transaction__MoneySchema-Input'];
      /**
       * Splits
       * @description Split lines (must sum to amount)
       */
      splits: components['schemas']['SplitLineRequest'][];
      /** Payee Name */
      payee_name?: string | null;
      /** Memo */
      memo?: string | null;
      /** Check Number */
      check_number?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HealthResponse
     * @description Health check response.
     */
    HealthResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: 'healthy' | 'unhealthy';
      /** Environment */
      environment: string;
      /**
       * Version
       * @default 0.1.0
       */
      version: string;
    };
    /**
     * HouseholdResponse
     * @description Nested household info in user profile response.
     */
    HouseholdResponse: {
      /**
       * Id
       * @description Household ID (hh_xxx format)
       */
      id: string;
      /**
       * Name
       * @description Household display name
       */
      name: string;
      /**
       * Is Owner
       * @description Whether user owns this household
       */
      is_owner: boolean;
    };
    /**
     * InstitutionSchema
     * @description Schema for InstitutionDetails value object.
     */
    InstitutionSchema: {
      /**
       * Name
       * @description Institution name
       */
      name: string;
      /** Website */
      website?: string | null;
      /** Phone */
      phone?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * MarkClearedRequest
     * @description Request to mark transaction as cleared.
     */
    MarkClearedRequest: {
      /**
       * Posted Date
       * @description Posted date (optional)
       */
      posted_date?: string | null;
    };
    /**
     * MoneySchema
     * @description Schema for Money value object serialization.
     */
    MoneySchema: {
      /**
       * Amount
       * @description Monetary amount with up to 4 decimal places
       */
      amount: string;
      /**
       * Currency
       * @description ISO 4217 3-letter currency code
       * @default USD
       */
      currency: string;
    };
    /**
     * RegisterRequest
     * @description Request schema for user registration.
     *
     *     Validates email format, password complexity, and display name.
     */
    RegisterRequest: {
      /**
       * Email
       * Format: email
       * @description User email address
       */
      email: string;
      /**
       * Password
       * @description Password (8+ chars, mixed case, number, symbol)
       */
      password: string;
      /**
       * Display Name
       * @description User display name
       */
      display_name: string;
      /**
       * Household Name
       * @description Household name (defaults to '{display_name}'s Household')
       */
      household_name?: string | null;
    };
    /**
     * RegisterResponse
     * @description Response schema for successful registration.
     */
    RegisterResponse: {
      /**
       * Message
       * @description Success message
       */
      message: string;
      /**
       * User Id
       * @description Created user ID
       */
      user_id: string;
      /**
       * Email
       * @description Registered email
       */
      email: string;
    };
    /**
     * RewardsBalanceSchema
     * @description Schema for RewardsBalance value object.
     */
    'RewardsBalanceSchema-Input': {
      /**
       * Value
       * @description Number of points/miles
       */
      value: number | string;
      /**
       * Unit
       * @description Reward program name (e.g., 'Alaska Miles')
       */
      unit: string;
    };
    /**
     * RewardsBalanceSchema
     * @description Schema for RewardsBalance value object.
     */
    'RewardsBalanceSchema-Output': {
      /**
       * Value
       * @description Number of points/miles
       */
      value: string;
      /**
       * Unit
       * @description Reward program name (e.g., 'Alaska Miles')
       */
      unit: string;
    };
    /**
     * SplitLineRequest
     * @description Request schema for a split line.
     */
    SplitLineRequest: {
      /**
       * Id
       * @description Split ID (omit for new splits)
       */
      id?: string | null;
      amount: components['schemas']['src__adapters__api__schemas__transaction__MoneySchema-Input'];
      /**
       * Category Id
       * @description Category for expense/income splits
       */
      category_id?: string | null;
      /**
       * Transfer Account Id
       * @description Target account for transfer splits
       */
      transfer_account_id?: string | null;
      /** Memo */
      memo?: string | null;
    };
    /**
     * SplitLineResponse
     * @description Response schema for a split line.
     */
    SplitLineResponse: {
      /** Id */
      id: string;
      amount: components['schemas']['src__adapters__api__schemas__transaction__MoneySchema-Output'];
      /** Category Id */
      category_id: string | null;
      /** Transfer Account Id */
      transfer_account_id: string | null;
      /** Memo */
      memo: string | null;
    };
    /**
     * TokenResponse
     * @description OAuth2-compatible token response.
     */
    TokenResponse: {
      /**
       * Access Token
       * @description JWT access token
       */
      access_token: string;
      /**
       * Token Type
       * @description Token type
       * @default bearer
       */
      token_type: string;
      /**
       * Expires In
       * @description Token lifetime in seconds
       * @default 900
       */
      expires_in: number;
    };
    /**
     * TransactionListResponse
     * @description Response for listing transactions.
     */
    TransactionListResponse: {
      /** Transactions */
      transactions: components['schemas']['TransactionResponse'][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /**
     * TransactionResponse
     * @description Response schema for a transaction.
     */
    TransactionResponse: {
      /** Id */
      id: string;
      /** User Id */
      user_id: string;
      /** Account Id */
      account_id: string;
      /**
       * Effective Date
       * Format: date
       */
      effective_date: string;
      /** Posted Date */
      posted_date: string | null;
      amount: components['schemas']['src__adapters__api__schemas__transaction__MoneySchema-Output'];
      status: components['schemas']['TransactionStatus'];
      source: components['schemas']['TransactionSource'];
      /** Splits */
      splits: components['schemas']['SplitLineResponse'][];
      /** Payee Id */
      payee_id: string | null;
      /** Payee Name */
      payee_name: string | null;
      /** Memo */
      memo: string | null;
      /** Check Number */
      check_number: string | null;
      /** Is Mirror */
      is_mirror: boolean;
      /** Source Transaction Id */
      source_transaction_id: string | null;
      /** Source Split Id */
      source_split_id: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * TransactionSource
     * @description Source of transaction creation.
     *
     *     Indicates how a transaction was created for Phase 6 linking model:
     *     - MANUAL: User-entered transaction
     *     - DOWNLOADED: Imported from bank sync
     * @enum {string}
     */
    TransactionSource: 'manual' | 'downloaded';
    /**
     * TransactionStatus
     * @description Transaction status progression.
     *
     *     Status values representing the lifecycle of a transaction:
     *     - PENDING: Default for new transactions, not yet cleared
     *     - CLEARED: Posted/cleared to the account
     *     - RECONCILED: Verified against bank statement
     * @enum {string}
     */
    TransactionStatus: 'pending' | 'cleared' | 'reconciled';
    /**
     * UpdateAccountRequest
     * @description Request schema for updating an account.
     */
    UpdateAccountRequest: {
      /** Name */
      name?: string | null;
      institution?: components['schemas']['InstitutionSchema'] | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * UpdateCategoryRequest
     * @description Request to update a category.
     */
    UpdateCategoryRequest: {
      /** Name */
      name?: string | null;
      /**
       * Parent Id
       * @description New parent ID (or null for top-level)
       */
      parent_id?: string | null;
      /** Icon */
      icon?: string | null;
    };
    /**
     * UpdateTransactionRequest
     * @description Request to update transaction metadata or splits.
     *
     *     Supports two modes:
     *     1. Metadata only: Update dates, memo, payee, check_number
     *     2. Full update: Include splits and amount to change financial allocations
     *
     *     When updating splits, amount is required and mirror transactions are synced.
     */
    UpdateTransactionRequest: {
      /** Effective Date */
      effective_date?: string | null;
      /** Posted Date */
      posted_date?: string | null;
      /** Memo */
      memo?: string | null;
      /** Payee Name */
      payee_name?: string | null;
      /** Check Number */
      check_number?: string | null;
      /**
       * Splits
       * @description New splits (if provided, amount must also be provided)
       */
      splits?: components['schemas']['SplitLineRequest'][] | null;
      /** @description New amount (required if splits provided) */
      amount?:
        | components['schemas']['src__adapters__api__schemas__transaction__MoneySchema-Input']
        | null;
    };
    /**
     * UserProfileResponse
     * @description User profile with household info.
     *
     *     Returned by GET /auth/me for displaying user context (welcome message,
     *     household info) in the frontend. Prepares is_owner flag for Phase 25
     *     (Multi-User Households).
     */
    UserProfileResponse: {
      /**
       * User Id
       * @description User ID (user_xxx format)
       */
      user_id: string;
      /**
       * Email
       * @description User email address
       */
      email: string;
      /**
       * Display Name
       * @description User display name
       */
      display_name: string;
      /**
       * Email Verified
       * @description Whether email is verified
       */
      email_verified: boolean;
      /**
       * Created At
       * Format: date-time
       * @description Account creation timestamp (member since)
       */
      created_at: string;
      /** @description User's household info */
      household: components['schemas']['HouseholdResponse'];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * VerifyEmailResponse
     * @description Response schema for email verification.
     */
    VerifyEmailResponse: {
      /**
       * Message
       * @description Verification message
       */
      message: string;
      /**
       * User Id
       * @description Verified user ID
       */
      user_id: string;
      /**
       * Email
       * @description Verified email address
       */
      email: string;
    };
    /**
     * MoneySchema
     * @description Schema for money amounts.
     */
    'src__adapters__api__schemas__transaction__MoneySchema-Input': {
      /**
       * Amount
       * @description Monetary amount with up to 4 decimal places
       */
      amount: number | string;
      /**
       * Currency
       * @description ISO 4217 3-letter currency code
       * @default USD
       */
      currency: string;
    };
    /**
     * MoneySchema
     * @description Schema for money amounts.
     */
    'src__adapters__api__schemas__transaction__MoneySchema-Output': {
      /**
       * Amount
       * @description Monetary amount with up to 4 decimal places
       */
      amount: string;
      /**
       * Currency
       * @description ISO 4217 3-letter currency code
       * @default USD
       */
      currency: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  readiness_check_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: boolean;
          };
        };
      };
    };
  };
  register_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RegisterResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_auth_token_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': components['schemas']['Body_login_auth_token_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_token_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        refresh_token?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  verify_email_auth_verify_get: {
    parameters: {
      query: {
        /** @description Email verification token */
        token: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VerifyEmailResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_current_user_profile_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserProfileResponse'];
        };
      };
    };
  };
  create_checking_account_api_v1_accounts_checking_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCheckingAccountRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_savings_account_api_v1_accounts_savings_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSavingsAccountRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_credit_card_account_api_v1_accounts_credit_card_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCreditCardAccountRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_loan_account_api_v1_accounts_loan_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateLoanAccountRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_brokerage_account_api_v1_accounts_brokerage_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateBrokerageAccountRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_ira_account_api_v1_accounts_ira_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateIraAccountRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_rewards_account_api_v1_accounts_rewards_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRewardsAccountRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_accounts_api_v1_accounts_get: {
    parameters: {
      query?: {
        /** @description Filter by status */
        status?: components['schemas']['AccountStatus'] | null;
        /** @description Filter by account type */
        type?: components['schemas']['AccountType'] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_account_api_v1_accounts__account_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_account_api_v1_accounts__account_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_account_api_v1_accounts__account_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAccountRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  close_account_api_v1_accounts__account_id__close_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reopen_account_api_v1_accounts__account_id__reopen_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_categories_api_v1_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryListResponse'];
        };
      };
    };
  };
  create_category_api_v1_categories_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCategoryRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_category_tree_api_v1_categories_tree_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryTreeResponse'];
        };
      };
    };
  };
  get_category_api_v1_categories__category_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_category_api_v1_categories__category_id__delete: {
    parameters: {
      query?: {
        /** @description Category to reassign transactions to */
        reassign_to?: string | null;
      };
      header?: never;
      path: {
        category_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_category_api_v1_categories__category_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCategoryRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_transactions_api_v1_transactions_get: {
    parameters: {
      query?: {
        account_id?: string | null;
        category_id?: string | null;
        date_from?: string | null;
        date_to?: string | null;
        amount_min?: number | string | null;
        amount_max?: number | string | null;
        /** @description Full-text search */
        search?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransactionListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_transaction_api_v1_transactions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTransactionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransactionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_transaction_api_v1_transactions__transaction_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transaction_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransactionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_transaction_api_v1_transactions__transaction_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transaction_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_transaction_api_v1_transactions__transaction_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transaction_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTransactionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransactionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  mark_transaction_cleared_api_v1_transactions__transaction_id__clear_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transaction_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['MarkClearedRequest'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransactionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  mark_transaction_reconciled_api_v1_transactions__transaction_id__reconcile_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transaction_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransactionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
